/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineEmailUnsubscribeArgs = IDL.Record({
  'recipient_email' : IDL.Text,
  'topic_id' : IDL.Nat32,
});
export const _UnsubscribeSuccess = IDL.Record({
  'topic_name' : IDL.Opt(IDL.Text),
});
export const _UnsubscribeError = IDL.Record({});
export const _CaffeineEmailUnsubscribeResult = IDL.Variant({
  'Ok' : _UnsubscribeSuccess,
  'Err' : _UnsubscribeError,
});
export const TickerMessage = IDL.Record({
  'id' : IDL.Nat,
  'message' : IDL.Text,
});
export const DayStat = IDL.Record({ 'date' : IDL.Text, 'count' : IDL.Nat });
export const Timestamp = IDL.Int;
export const DripEmailLog = IDL.Record({
  'subscriberEmail' : IDL.Text,
  'templateId' : IDL.Nat,
  'sentAt' : Timestamp,
  'versionSent' : IDL.Nat,
});
export const DripTemplate = IDL.Record({
  'id' : IDL.Nat,
  'htmlBody' : IDL.Text,
  'delayDays' : IDL.Nat,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'version' : IDL.Nat,
  'updatedAt' : Timestamp,
});
export const EmailSignup = IDL.Record({
  'email' : IDL.Text,
  'signedUpAt' : Timestamp,
  'firstName' : IDL.Text,
});
export const UserId = IDL.Principal;
export const QrEntry = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'compositeImage' : IDL.Opt(IDL.Text),
  'userId' : UserId,
  'generatedAt' : Timestamp,
  'notes' : IDL.Text,
});
export const PaymentRecord = IDL.Record({
  'userId' : UserId,
  'timestamp' : Timestamp,
  'amountE8s' : IDL.Nat,
});
export const StylePreset = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'logoData' : IDL.Opt(IDL.Text),
  'dotColor' : IDL.Text,
  'bgColor' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineEmailUnsubscribeFromTopic' : IDL.Func(
      [_CaffeineEmailUnsubscribeArgs],
      [_CaffeineEmailUnsubscribeResult],
      [],
    ),
  'addTickerMessage' : IDL.Func([IDL.Text], [IDL.Opt(TickerMessage)], []),
  'broadcastToSubscribers' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'claimAdmin' : IDL.Func([], [IDL.Bool], []),
  'deleteQrEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteStylePreset' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteTickerMessage' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAdminPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getAdminStats' : IDL.Func([], [IDL.Vec(DayStat)], ['query']),
  'getAnalyticsAccess' : IDL.Func([], [IDL.Bool], ['query']),
  'getDripEmailLog' : IDL.Func([], [IDL.Vec(DripEmailLog)], ['query']),
  'getDripTemplates' : IDL.Func([], [IDL.Vec(DripTemplate)], ['query']),
  'getEmailSignups' : IDL.Func([], [IDL.Vec(EmailSignup)], []),
  'getMyClickCounts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getMyQrEntries' : IDL.Func([], [IDL.Vec(QrEntry)], []),
  'getMyStats' : IDL.Func([], [IDL.Vec(DayStat)], ['query']),
  'getPaymentLedger' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'getQrForRedirect' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Record({ 'url' : IDL.Text }))],
      [],
    ),
  'getStylePresets' : IDL.Func([], [IDL.Vec(StylePreset)], []),
  'getTickerMessages' : IDL.Func([], [IDL.Vec(TickerMessage)], ['query']),
  'removeEmailSignup' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'saveQrEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [QrEntry],
      [],
    ),
  'saveStylePreset' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [StylePreset],
      [],
    ),
  'signUpForEmail' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'unlockAnalytics' : IDL.Func(
      [IDL.Nat64],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateDripTemplate' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateTickerMessage' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineEmailUnsubscribeArgs = IDL.Record({
    'recipient_email' : IDL.Text,
    'topic_id' : IDL.Nat32,
  });
  const _UnsubscribeSuccess = IDL.Record({ 'topic_name' : IDL.Opt(IDL.Text) });
  const _UnsubscribeError = IDL.Record({});
  const _CaffeineEmailUnsubscribeResult = IDL.Variant({
    'Ok' : _UnsubscribeSuccess,
    'Err' : _UnsubscribeError,
  });
  const TickerMessage = IDL.Record({ 'id' : IDL.Nat, 'message' : IDL.Text });
  const DayStat = IDL.Record({ 'date' : IDL.Text, 'count' : IDL.Nat });
  const Timestamp = IDL.Int;
  const DripEmailLog = IDL.Record({
    'subscriberEmail' : IDL.Text,
    'templateId' : IDL.Nat,
    'sentAt' : Timestamp,
    'versionSent' : IDL.Nat,
  });
  const DripTemplate = IDL.Record({
    'id' : IDL.Nat,
    'htmlBody' : IDL.Text,
    'delayDays' : IDL.Nat,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'version' : IDL.Nat,
    'updatedAt' : Timestamp,
  });
  const EmailSignup = IDL.Record({
    'email' : IDL.Text,
    'signedUpAt' : Timestamp,
    'firstName' : IDL.Text,
  });
  const UserId = IDL.Principal;
  const QrEntry = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'compositeImage' : IDL.Opt(IDL.Text),
    'userId' : UserId,
    'generatedAt' : Timestamp,
    'notes' : IDL.Text,
  });
  const PaymentRecord = IDL.Record({
    'userId' : UserId,
    'timestamp' : Timestamp,
    'amountE8s' : IDL.Nat,
  });
  const StylePreset = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'logoData' : IDL.Opt(IDL.Text),
    'dotColor' : IDL.Text,
    'bgColor' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineEmailUnsubscribeFromTopic' : IDL.Func(
        [_CaffeineEmailUnsubscribeArgs],
        [_CaffeineEmailUnsubscribeResult],
        [],
      ),
    'addTickerMessage' : IDL.Func([IDL.Text], [IDL.Opt(TickerMessage)], []),
    'broadcastToSubscribers' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'claimAdmin' : IDL.Func([], [IDL.Bool], []),
    'deleteQrEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteStylePreset' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteTickerMessage' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAdminPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getAdminStats' : IDL.Func([], [IDL.Vec(DayStat)], ['query']),
    'getAnalyticsAccess' : IDL.Func([], [IDL.Bool], ['query']),
    'getDripEmailLog' : IDL.Func([], [IDL.Vec(DripEmailLog)], ['query']),
    'getDripTemplates' : IDL.Func([], [IDL.Vec(DripTemplate)], ['query']),
    'getEmailSignups' : IDL.Func([], [IDL.Vec(EmailSignup)], []),
    'getMyClickCounts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getMyQrEntries' : IDL.Func([], [IDL.Vec(QrEntry)], []),
    'getMyStats' : IDL.Func([], [IDL.Vec(DayStat)], ['query']),
    'getPaymentLedger' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
    'getQrForRedirect' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Record({ 'url' : IDL.Text }))],
        [],
      ),
    'getStylePresets' : IDL.Func([], [IDL.Vec(StylePreset)], []),
    'getTickerMessages' : IDL.Func([], [IDL.Vec(TickerMessage)], ['query']),
    'removeEmailSignup' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'saveQrEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [QrEntry],
        [],
      ),
    'saveStylePreset' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [StylePreset],
        [],
      ),
    'signUpForEmail' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'unlockAnalytics' : IDL.Func(
        [IDL.Nat64],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateDripTemplate' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateTickerMessage' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };