/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DayStat { 'date' : string, 'count' : bigint }
export interface DripEmailLog {
  'subscriberEmail' : string,
  'templateId' : bigint,
  'sentAt' : Timestamp,
  'versionSent' : bigint,
}
export interface DripTemplate {
  'id' : bigint,
  'htmlBody' : string,
  'delayDays' : bigint,
  'subject' : string,
  'name' : string,
  'version' : bigint,
  'updatedAt' : Timestamp,
}
export interface EmailSignup {
  'email' : string,
  'signedUpAt' : Timestamp,
  'firstName' : string,
}
export interface PaymentRecord {
  'userId' : UserId,
  'timestamp' : Timestamp,
  'amountE8s' : bigint,
}
export interface QrEntry {
  'id' : bigint,
  'url' : string,
  'compositeImage' : [] | [string],
  'userId' : UserId,
  'generatedAt' : Timestamp,
  'notes' : string,
}
export interface StylePreset {
  'id' : bigint,
  'name' : string,
  'logoData' : [] | [string],
  'dotColor' : string,
  'bgColor' : string,
}
export interface TickerMessage { 'id' : bigint, 'message' : string }
export type Timestamp = bigint;
export type UserId = Principal;
export interface _CaffeineEmailUnsubscribeArgs {
  'recipient_email' : string,
  'topic_id' : number,
}
export type _CaffeineEmailUnsubscribeResult = { 'Ok' : _UnsubscribeSuccess } |
  { 'Err' : _UnsubscribeError };
export type _UnsubscribeError = {};
export interface _UnsubscribeSuccess { 'topic_name' : [] | [string] }
export interface _SERVICE {
  '_caffeineEmailUnsubscribeFromTopic' : ActorMethod<
    [_CaffeineEmailUnsubscribeArgs],
    _CaffeineEmailUnsubscribeResult
  >,
  'addTickerMessage' : ActorMethod<[string], [] | [TickerMessage]>,
  'broadcastToSubscribers' : ActorMethod<[string, string], string>,
  'claimAdmin' : ActorMethod<[], boolean>,
  'deleteQrEntry' : ActorMethod<[bigint], boolean>,
  'deleteStylePreset' : ActorMethod<[bigint], boolean>,
  'deleteTickerMessage' : ActorMethod<[bigint], boolean>,
  'getAdminPrincipal' : ActorMethod<[], [] | [Principal]>,
  'getAdminStats' : ActorMethod<[], Array<DayStat>>,
  'getAnalyticsAccess' : ActorMethod<[], boolean>,
  'getDripEmailLog' : ActorMethod<[], Array<DripEmailLog>>,
  'getDripTemplates' : ActorMethod<[], Array<DripTemplate>>,
  'getEmailSignups' : ActorMethod<[], Array<EmailSignup>>,
  'getMyClickCounts' : ActorMethod<[], Array<[string, bigint]>>,
  'getMyQrEntries' : ActorMethod<[], Array<QrEntry>>,
  'getMyStats' : ActorMethod<[], Array<DayStat>>,
  'getPaymentLedger' : ActorMethod<[], Array<PaymentRecord>>,
  'getQrForRedirect' : ActorMethod<[string], [] | [{ 'url' : string }]>,
  'getStylePresets' : ActorMethod<[], Array<StylePreset>>,
  'getTickerMessages' : ActorMethod<[], Array<TickerMessage>>,
  'removeEmailSignup' : ActorMethod<[string], boolean>,
  'saveQrEntry' : ActorMethod<[string, string, [] | [string]], QrEntry>,
  'saveStylePreset' : ActorMethod<
    [string, string, string, [] | [string]],
    StylePreset
  >,
  'signUpForEmail' : ActorMethod<[string, string], boolean>,
  'unlockAnalytics' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateDripTemplate' : ActorMethod<[bigint, string, string], boolean>,
  'updateTickerMessage' : ActorMethod<[bigint, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];