/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _UnsubscribeError {
}
export type Timestamp = bigint;
export interface EmailSignup {
    email: string;
    signedUpAt: Timestamp;
    firstName: string;
}
export interface PaymentRecord {
    userId: UserId;
    timestamp: Timestamp;
    amountE8s: bigint;
}
export interface DripEmailLog {
    subscriberEmail: string;
    templateId: bigint;
    sentAt: Timestamp;
    versionSent: bigint;
}
export interface TickerMessage {
    id: bigint;
    message: string;
}
export type _CaffeineEmailUnsubscribeResult = {
    __kind__: "Ok";
    Ok: _UnsubscribeSuccess;
} | {
    __kind__: "Err";
    Err: _UnsubscribeError;
};
export interface DripTemplate {
    id: bigint;
    htmlBody: string;
    delayDays: bigint;
    subject: string;
    name: string;
    version: bigint;
    updatedAt: Timestamp;
}
export type UserId = Principal;
export interface DayStat {
    date: string;
    count: bigint;
}
export interface _UnsubscribeSuccess {
    topic_name?: string;
}
export interface _CaffeineEmailUnsubscribeArgs {
    recipient_email: string;
    topic_id: number;
}
export interface StylePreset {
    id: bigint;
    name: string;
    logoData?: string;
    dotColor: string;
    bgColor: string;
}
export interface QrEntry {
    id: bigint;
    url: string;
    compositeImage?: string;
    userId: UserId;
    generatedAt: Timestamp;
    notes: string;
}
export interface backendInterface {
    _caffeineEmailUnsubscribeFromTopic(args: _CaffeineEmailUnsubscribeArgs): Promise<_CaffeineEmailUnsubscribeResult>;
    addTickerMessage(message: string): Promise<TickerMessage | null>;
    broadcastToSubscribers(subject: string, body: string): Promise<string>;
    claimAdmin(): Promise<boolean>;
    deleteQrEntry(entryId: bigint): Promise<boolean>;
    deleteStylePreset(id: bigint): Promise<boolean>;
    deleteTickerMessage(id: bigint): Promise<boolean>;
    getAdminPrincipal(): Promise<Principal | null>;
    getAdminStats(): Promise<Array<DayStat>>;
    getAnalyticsAccess(): Promise<boolean>;
    getDripEmailLog(): Promise<Array<DripEmailLog>>;
    getDripTemplates(): Promise<Array<DripTemplate>>;
    getEmailSignups(): Promise<Array<EmailSignup>>;
    getMyClickCounts(): Promise<Array<[string, bigint]>>;
    getMyQrEntries(): Promise<Array<QrEntry>>;
    getMyStats(): Promise<Array<DayStat>>;
    getPaymentLedger(): Promise<Array<PaymentRecord>>;
    getQrForRedirect(id: string): Promise<{
        url: string;
    } | null>;
    getStylePresets(): Promise<Array<StylePreset>>;
    getTickerMessages(): Promise<Array<TickerMessage>>;
    removeEmailSignup(email: string): Promise<boolean>;
    saveQrEntry(url: string, notes: string, compositeImage: string | null): Promise<QrEntry>;
    saveStylePreset(name: string, dotColor: string, bgColor: string, logoData: string | null): Promise<StylePreset>;
    signUpForEmail(firstName: string, email: string): Promise<boolean>;
    unlockAnalytics(blockHeight: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateDripTemplate(id: bigint, subject: string, htmlBody: string): Promise<boolean>;
    updateTickerMessage(id: bigint, message: string): Promise<boolean>;
}
import type { QrEntry as _QrEntry, StylePreset as _StylePreset, TickerMessage as _TickerMessage, Timestamp as _Timestamp, UserId as _UserId, _CaffeineEmailUnsubscribeResult as __CaffeineEmailUnsubscribeResult, _UnsubscribeError as __UnsubscribeError, _UnsubscribeSuccess as __UnsubscribeSuccess } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineEmailUnsubscribeFromTopic(arg0: _CaffeineEmailUnsubscribeArgs): Promise<_CaffeineEmailUnsubscribeResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineEmailUnsubscribeFromTopic(arg0);
                return from_candid__CaffeineEmailUnsubscribeResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineEmailUnsubscribeFromTopic(arg0);
            return from_candid__CaffeineEmailUnsubscribeResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addTickerMessage(arg0: string): Promise<TickerMessage | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addTickerMessage(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTickerMessage(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async broadcastToSubscribers(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.broadcastToSubscribers(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.broadcastToSubscribers(arg0, arg1);
            return result;
        }
    }
    async claimAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.claimAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimAdmin();
            return result;
        }
    }
    async deleteQrEntry(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQrEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQrEntry(arg0);
            return result;
        }
    }
    async deleteStylePreset(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStylePreset(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStylePreset(arg0);
            return result;
        }
    }
    async deleteTickerMessage(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTickerMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTickerMessage(arg0);
            return result;
        }
    }
    async getAdminPrincipal(): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminPrincipal();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminPrincipal();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminStats(): Promise<Array<DayStat>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats();
            return result;
        }
    }
    async getAnalyticsAccess(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalyticsAccess();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalyticsAccess();
            return result;
        }
    }
    async getDripEmailLog(): Promise<Array<DripEmailLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDripEmailLog();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDripEmailLog();
            return result;
        }
    }
    async getDripTemplates(): Promise<Array<DripTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDripTemplates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDripTemplates();
            return result;
        }
    }
    async getEmailSignups(): Promise<Array<EmailSignup>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmailSignups();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmailSignups();
            return result;
        }
    }
    async getMyClickCounts(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyClickCounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyClickCounts();
            return result;
        }
    }
    async getMyQrEntries(): Promise<Array<QrEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyQrEntries();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyQrEntries();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyStats(): Promise<Array<DayStat>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyStats();
            return result;
        }
    }
    async getPaymentLedger(): Promise<Array<PaymentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentLedger();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentLedger();
            return result;
        }
    }
    async getQrForRedirect(arg0: string): Promise<{
        url: string;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQrForRedirect(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQrForRedirect(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStylePresets(): Promise<Array<StylePreset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStylePresets();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStylePresets();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTickerMessages(): Promise<Array<TickerMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTickerMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTickerMessages();
            return result;
        }
    }
    async removeEmailSignup(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeEmailSignup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeEmailSignup(arg0);
            return result;
        }
    }
    async saveQrEntry(arg0: string, arg1: string, arg2: string | null): Promise<QrEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.saveQrEntry(arg0, arg1, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg2));
                return from_candid_QrEntry_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveQrEntry(arg0, arg1, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg2));
            return from_candid_QrEntry_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveStylePreset(arg0: string, arg1: string, arg2: string, arg3: string | null): Promise<StylePreset> {
        if (this.processError) {
            try {
                const result = await this.actor.saveStylePreset(arg0, arg1, arg2, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg3));
                return from_candid_StylePreset_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveStylePreset(arg0, arg1, arg2, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg3));
            return from_candid_StylePreset_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async signUpForEmail(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.signUpForEmail(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.signUpForEmail(arg0, arg1);
            return result;
        }
    }
    async unlockAnalytics(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.unlockAnalytics(arg0);
                return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlockAnalytics(arg0);
            return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateDripTemplate(arg0: bigint, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDripTemplate(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDripTemplate(arg0, arg1, arg2);
            return result;
        }
    }
    async updateTickerMessage(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTickerMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTickerMessage(arg0, arg1);
            return result;
        }
    }
}
function from_candid_QrEntry_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QrEntry): QrEntry {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_StylePreset_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StylePreset): StylePreset {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineEmailUnsubscribeResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineEmailUnsubscribeResult): _CaffeineEmailUnsubscribeResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid__UnsubscribeSuccess_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __UnsubscribeSuccess): _UnsubscribeSuccess {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        url: string;
    }]): {
    url: string;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TickerMessage]): TickerMessage | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    url: string;
    compositeImage: [] | [string];
    userId: _UserId;
    generatedAt: _Timestamp;
    notes: string;
}): {
    id: bigint;
    url: string;
    compositeImage?: string;
    userId: UserId;
    generatedAt: Timestamp;
    notes: string;
} {
    return {
        id: value.id,
        url: value.url,
        compositeImage: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.compositeImage)),
        userId: value.userId,
        generatedAt: value.generatedAt,
        notes: value.notes
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    logoData: [] | [string];
    dotColor: string;
    bgColor: string;
}): {
    id: bigint;
    name: string;
    logoData?: string;
    dotColor: string;
    bgColor: string;
} {
    return {
        id: value.id,
        name: value.name,
        logoData: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.logoData)),
        dotColor: value.dotColor,
        bgColor: value.bgColor
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    topic_name: [] | [string];
}): {
    topic_name?: string;
} {
    return {
        topic_name: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.topic_name))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Ok: __UnsubscribeSuccess;
} | {
    Err: __UnsubscribeError;
}): {
    __kind__: "Ok";
    Ok: _UnsubscribeSuccess;
} | {
    __kind__: "Err";
    Err: _UnsubscribeError;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid__UnsubscribeSuccess_n3(_uploadFile, _downloadFile, value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StylePreset>): Array<StylePreset> {
    return value.map((x)=>from_candid_StylePreset_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QrEntry>): Array<QrEntry> {
    return value.map((x)=>from_candid_QrEntry_n9(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
